# Generated by Django 5.0.8 on 2024-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=105)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=9)),
            ],
        ),
    ]
