# Generated by Django 5.0.8 on 2024-09-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0002_alter_aluno_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('siape', models.CharField(max_length=14, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=9, verbose_name='RG')),
            ],
        ),
    ]
