# Generated by Django 5.0.8 on 2024-09-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('qtde_creditos', models.IntegerField(default=4, verbose_name='Créditos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='Data Finalização')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acad.professor', verbose_name='Coodenador')),
            ],
        ),
    ]
