# Generated by Django 5.0.8 on 2024-12-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0004_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Sensor')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Sensor',
                'verbose_name_plural': 'Tipos de Sensores',
                'db_table': 'tb_tipo_sensor',
            },
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
