# Generated by Django 5.0.8 on 2025-01-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0005_tiposensor_delete_curso_delete_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSensorFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Sensor Físico')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Sensor',
                'verbose_name_plural': 'Tipos de Sensores',
                'db_table': 'tb_tipo_sensor_fisico',
            },
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
