# Generated by Django 5.0.8 on 2025-01-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0006_tiposensorfisico_delete_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposensorfisico',
            options={'verbose_name': 'Tipo de Sensor Físico', 'verbose_name_plural': 'Tipos de Sensores Físicos'},
        ),
    ]
