# Generated by Django 5.0.8 on 2025-01-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0010_tipopavimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Orientação')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição da Orientação')),
            ],
            options={
                'verbose_name': 'Tipo de Orientação',
                'verbose_name_plural': 'Tipos de Orientações',
                'db_table': 'tb_tipo_orientacao',
            },
        ),
        migrations.AlterField(
            model_name='tipoparametro',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Parâmetro'),
        ),
        migrations.AlterField(
            model_name='tipopavimento',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Pavimento'),
        ),
    ]
