# Generated by Django 5.0.8 on 2025-01-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0011_tipoorientacao_alter_tipoparametro_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoparametro',
            name='sigla',
        ),
    ]
