# Generated by Django 5.0.8 on 2025-01-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0012_remove_tipoparametro_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Sala')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('orientacao', models.ForeignKey(db_column='id_orientacao', on_delete=django.db.models.deletion.PROTECT, to='acad.tipoorientacao')),
                ('pavimento', models.ForeignKey(db_column='id_pavimnto', on_delete=django.db.models.deletion.PROTECT, to='acad.tipopavimento')),
            ],
            options={
                'verbose_name': 'Tipo de Sala',
                'verbose_name_plural': 'Tipos de Salas',
                'db_table': 'tb_tipo_sala',
            },
        ),
    ]
