# Generated by Django 5.0.8 on 2025-02-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0014_medicaoclimatica_alter_tipoparametro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposensorfisico',
            name='tensao_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Tensão Máxima'),
        ),
        migrations.AddField(
            model_name='tiposensorfisico',
            name='tensao_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Tensão Mínima'),
        ),
    ]
