# Generated by Django 5.0.8 on 2025-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0015_tiposensorfisico_tensao_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposensor',
            name='limite_inferior_permitido',
            field=models.FloatField(blank=True, null=True, verbose_name='Limite Inferior Permitido'),
        ),
        migrations.AddField(
            model_name='tiposensor',
            name='limite_superior_permitido',
            field=models.FloatField(blank=True, null=True, verbose_name='Limite Superior Permitido'),
        ),
        migrations.AddField(
            model_name='tiposensor',
            name='unidade',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Unidade'),
        ),
    ]
