# Generated by Django 5.0.8 on 2025-02-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0016_tiposensor_limite_inferior_permitido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposensorlogico',
            name='id_sensor_fisico',
            field=models.ForeignKey(blank=True, db_column='id_sensor_fisico', null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.tiposensorfisico', verbose_name='Sensor Físico'),
        ),
        migrations.AddField(
            model_name='tiposensorlogico',
            name='id_tipo',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.tiposensor', verbose_name='Tipo de Sensor'),
        ),
    ]
