# Generated by Django 5.0.8 on 2025-02-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0017_tiposensorlogico_id_sensor_fisico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoparametro',
            name='id_sensor_logico',
            field=models.ForeignKey(blank=True, db_column='id_sensor_logico', null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.tiposensorlogico', verbose_name='Sensor Lógico'),
        ),
        migrations.AddField(
            model_name='tipoparametro',
            name='valor',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
