# Generated by Django 5.0.8 on 2025-02-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0019_remove_tipopavimento_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoorientacao',
            name='descricao',
        ),
    ]
