# Generated by Django 5.0.8 on 2025-02-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0021_remove_tipoparametro_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoparametro',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Registro'),
        ),
    ]
