# Generated by Django 5.0.8 on 2025-02-18 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0022_tipoparametro_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.PROTECT, to='acad.tiposala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'db_table': 'tb_leitura',
            },
        ),
    ]
