# Generated by Django 5.0.8 on 2025-02-18 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0023_leitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('id_leitura', models.ForeignKey(db_column='id_leitura', on_delete=django.db.models.deletion.PROTECT, to='acad.leitura', verbose_name='Leitura')),
                ('id_sensor_logico', models.ForeignKey(db_column='id_sensor_logico', on_delete=django.db.models.deletion.PROTECT, to='acad.tiposensorlogico', verbose_name='Sensor Lógico')),
            ],
            options={
                'verbose_name': 'Leitura de Sensor',
                'verbose_name_plural': 'Leituras de Sensores',
                'db_table': 'tb_leitura_sensor',
            },
        ),
    ]
