# Generated by Django 5.0.8 on 2025-02-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0024_leiturasensor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiposala',
            table='tb_sala',
        ),
    ]
