# Generated by Django 5.0.8 on 2025-02-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0025_alter_tiposala_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoparametro',
            name='data',
        ),
        migrations.RemoveField(
            model_name='tiposensor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tiposensor',
            name='sigla',
        ),
        migrations.RemoveField(
            model_name='tiposensorlogico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tiposensorlogico',
            name='sigla',
        ),
        migrations.AlterField(
            model_name='tiposala',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='tiposala',
            name='pavimento',
            field=models.ForeignKey(db_column='id_pavimento', on_delete=django.db.models.deletion.PROTECT, to='acad.tipopavimento'),
        ),
        migrations.AlterField(
            model_name='tiposala',
            name='sigla',
            field=models.CharField(max_length=10, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='descricao',
            field=models.CharField(default='Sem descricao', max_length=50, verbose_name='Sensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposensorlogico',
            name='descricao',
            field=models.CharField(default='', max_length=50, verbose_name='Sensor Lógico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposensorlogico',
            name='id_tipo_sensor',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.PROTECT, to='acad.tiposensor', verbose_name='Tipo de Sensor'),
        ),
        migrations.AlterModelTable(
            name='tipoorientacao',
            table='tb_orientacao',
        ),
        migrations.AlterModelTable(
            name='tipoparametro',
            table='tb_parametro',
        ),
        migrations.AlterModelTable(
            name='tipopavimento',
            table='tb_pavimento',
        ),
        migrations.AlterModelTable(
            name='tiposensorfisico',
            table='tb_sensor_fisico',
        ),
        migrations.AlterModelTable(
            name='tiposensorlogico',
            table='tb_sensor_logico',
        ),
    ]
