# Generated by Django 5.0.8 on 2025-02-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0026_remove_tipoparametro_data_remove_tiposensor_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposala',
            options={'managed': False, 'verbose_name': 'Tipo de Sala', 'verbose_name_plural': 'Tipos de Salas'},
        ),
    ]
